- name: Setup my local development environment
  hosts: localhost
  vars_files:
    - share.yml
  roles:
    - role: ohmyzsh
      tags: ['ohmyzsh']
    - role: common
      tags: ['common']
    - role: fzf
      tags: ['fzf']
    - role: mise
      tags: ['mise']
    - role: ghostty
      tags: ['ghostty']
    - role: tmux
      tags: ['tmux']
    - role: lazygit
      tags: ['lazygit']
    - role: lazysql
      tags: ['lazysql']
    - role: nvim
      tags: ['nvim']
    - role: aerospace
      tags: ['aerospace']
    - role: lpass
      tags: ['lpass']
