- name: Setup my local development environment
  hosts: localhost
  vars_files:
    - share.yml
  roles:
    - role: common
      tags: ['common']
    - role: fish
      tags: ['fish']
    - role: nvim
      tags: ['nvim']
    - role: omniwm
      tags: ['omniwm']
    - role: firefox
      tags: ['firefox']
    - role: ghostty
      tags: ['ghostty']
    - role: obsidian
      tags: ['obsidian']
