- name: Setup my local development environment
  hosts: localhost
  vars_files:
    - share.yml
  roles:
    - role: common
      tags: ['common']
    - role: mise
      tags: ['mise']
    - role: nushell
      tags: ['nushell']
    - role: nvim
      tags: ['nvim']
    - role: aerospace
      tags: ['aerospace']
    - role: ghostty
      tags: ['ghostty']
    - role: tmux
      tags: ['tmux']
