- name: Check if Oh My Zsh is installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_dir

- name: Install Oh My Zsh (if not installed)
  shell: |
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
  when: not ohmyzsh_dir.stat.exists

- name: Ensure zsh-autosuggestions plugin is installed
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Ensure fast-syntax-highlighting plugin is installed
  git:
    repo: https://github.com/zdharma-continuum/fast-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting"

- name: Configure .zshrc settings
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - 'export XDG_CONFIG_HOME="$HOME/.config"'
    - 'export ZSH="$HOME/.oh-my-zsh"'
    - 'ZSH_THEME="nicoulaj"'
    - 'plugins=(git z zsh-autosuggestions fast-syntax-highlighting)'
    - 'DISABLE_AUTO_UPDATE=true'
    - 'source $ZSH/oh-my-zsh.sh'

- name: Deploy Dracula fast-syntax-highlighting theme
  template:
    src: dracula_fsh.zsh.j2
    dest: "{{ ansible_env.HOME }}/.config/fsh/dracula.zsh"
    mode: '0644'

- name: Source Dracula fsh theme in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "source ~/.config/fsh/dracula.zsh"
    state: present

