export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="refined"
plugins=(git z zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# Edit current command line in $EDITOR (Option+Space)
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line
