export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="refined"
plugins=(git z zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# kitty-scrollback.nvim: edit current command line in nvim (Ctrl-x Ctrl-e)
autoload -Uz edit-command-line
zle -N edit-command-line

function kitty_scrollback_edit_command_line() {
  local VISUAL="$HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/scripts/edit_command_line.sh"
  zle edit-command-line
  zle kill-whole-line
}
zle -N kitty_scrollback_edit_command_line

bindkey '^e' kitty_scrollback_edit_command_line
