- name: Install nb via Homebrew
  community.general.homebrew:
    name: nb
    state: present

- name: Copy nbrc config
  template:
    src: nbrc.j2
    dest: "{{ ansible_env.HOME }}/.nbrc"
    backup: yes
