local function copy_path(expr, label)
  local path = vim.fn.expand(expr)
  vim.fn.setreg("+", path)
  vim.notify("Copied " .. label .. ": " .. path)
end

vim.keymap.set("n", "<leader>br", function()
  copy_path("%:.", "relative path")
end, { desc = "Copy relative path" })
vim.keymap.set("n", "<leader>ba", function()
  copy_path("%:p", "absolute path")
end, { desc = "Copy absolute path" })
vim.keymap.set("n", "<leader>bn", function()
  copy_path("%:t", "filename")
end, { desc = "Copy filename" })

vim.keymap.set("n", "<leader>qq", "<cmd>qa!<cr>", { desc = "Force quit all" })
vim.keymap.set("n", "<leader>qw", "<cmd>wqa<cr>", { desc = "Write and quit all" })
vim.keymap.set("n", "<leader>m", function()
  Snacks.notifier.show_history()
end, { desc = "Show messages" })
vim.keymap.set("n", "<leader>bb", "<cmd>e #<cr>", { desc = "Switch to alternate buffer" })
