- name: Install im-select (tap is added automatically by Homebrew)
  homebrew:
    name: daipeihust/tap/im-select
    state: present

- name: Install aerospace
  community.general.homebrew:
    name: aerospace
    state: present
    install_options: cask

- name: Ensure aerospace config directory exists 
  file:
    path: "{{ ansible_env.HOME }}/.config/aerospace"
    state: directory

- name: Copy default aerospace default config
  template:
    src: aerospace.j2
    dest: "{{ ansible_env.HOME }}/.config/aerospace/aerospace.toml"
    backup: yes

- name: Remove the origin config
  file:
    path: "{{ ansible_env.HOME }}/.aerospace.toml"
    state: absent

- name: Activate aerospace if not already running
  shell: "pgrep -x AeroSpace || open -a AeroSpace.app"
  changed_when: false
