- name: Install aerospace
  community.general.homebrew_cask:
    name: aerospace
    state: present

- name: Ensure aerospace config directory exists 
  file:
    path: "{{ ansible_env.HOME }}/.config/aerospace"
    state: directory

- name: Copy default aerospace default config 
  copy:
    src: aerospace
    dest: "~/.config/aerospace/aerospace.toml"
    backup: yes

- name: Remove the origin config
  file:
    path: "~/.aerospace.toml"
    state: absent
  ignore_errors: yes

- name: Activate aerospace globally
  shell: "open -a AeroSpace.app"
