- name: Install mise
  homebrew:
    name: mise
    state: present

- name: Ensure mise config directory exists
  file:
    path: "~/.config/mise"
    state: directory

- name: Copy the mise config file
  copy:
    src: "config"
    dest: "~/.config/mise/config.toml"
    backup: yes

- name: Ensure global tools installed
  shell: "mise install"
  changed_when: false
