- name: Install Kitty
  community.general.homebrew:
    name: kitty
    state: present
    install_options: cask

- name: Check if FiraCode Nerd Font is installed
  stat:
    path: "~/Library/Fonts/FiraCodeNerdFont-Bold.ttf"
  register: firacode_font

- name: Install FiraCode Nerd Font
  community.general.homebrew:
    name: font-fira-code-nerd-font
    state: present
    install_options: cask
  when: not firacode_font.stat.exists

- name: Ensure Kitty config directory exists
  file:
    path: "~/.config/kitty"
    state: directory

- name: Deploy Kitty config
  template:
    src: kitty.conf.j2
    dest: "~/.config/kitty/kitty.conf"
    backup: true
