- name: Install bat
  homebrew:
    name: bat
    state: present

- name: Install fzf
  homebrew:
    name: fzf
    state: present

- name: Ensure fzf config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/fzf"
    state: directory

- name: Copy fzf zsh config
  template:
    src: fzf.zsh.j2
    dest: "{{ ansible_env.HOME }}/.config/fzf/fzf.zsh"

- name: Source fzf.zsh from zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "source ~/.config/fzf/fzf.zsh"
    state: present

- name: Set PAGER environment variable
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PAGER=bat'
    state: present

- name: Install nb via Homebrew
  community.general.homebrew:
    name: nb
    state: present

- name: Copy nbrc config
  template:
    src: nbrc.j2
    dest: "{{ ansible_env.HOME }}/.nbrc"
    backup: yes
