// GENERATED by Ansible from share.yml — do not edit. Regenerate: ansible-playbook main.yml --tags kitty
use ratatui::style::Color;


pub(crate) const MAUVE: Color = Color::Rgb(189, 147, 249);
pub(crate) const ORANGE: Color = Color::Rgb(255, 184, 108);
pub(crate) const TEAL: Color = Color::Rgb(139, 233, 253);
pub(crate) const GREEN: Color = Color::Rgb(80, 250, 123);
pub(crate) const YELLOW: Color = Color::Rgb(241, 250, 140);
pub(crate) const PINK: Color = Color::Rgb(255, 121, 198);
pub(crate) const BRIGHT_CYAN: Color = Color::Rgb(164, 255, 255);
pub(crate) const FG: Color = Color::Rgb(248, 248, 242);
pub(crate) const COMMENT: Color = Color::Rgb(98, 114, 164);
pub(crate) const COMMENT_BRIGHT: Color = Color::Rgb(98, 114, 164);
pub(crate) const DRACULA_BG: Color = Color::Rgb(40, 42, 54);
pub(crate) const PILL_BG: Color = Color::Rgb(68, 71, 90);
/// Kube context pill fill — uses `bright_cyan` from share palette.
pub(crate) const KUBE_PILL_BG: Color = BRIGHT_CYAN;
