- name: Install WezTerm
  community.general.homebrew:
    name: wezterm
    state: present
    install_options: cask

- name: Check if FiraCode Nerd Font is installed
  stat:
    path: "~/Library/Fonts/FiraCodeNerdFont-Bold.ttf"
  register: firacode_font

- name: Install FiraCode Nerd Font
  community.general.homebrew:
    name: font-fira-code-nerd-font
    state: present
    install_options: cask
  when: not firacode_font.stat.exists

- name: Ensure WezTerm config directory exists
  file:
    path: "~/.config/wezterm"
    state: directory

- name: Deploy WezTerm config
  template:
    src: wezterm.lua.j2
    dest: "~/.config/wezterm/wezterm.lua"
    backup: true
