- name: Install Ghostty
  community.general.homebrew:
    name: ghostty
    state: present
    install_options: cask

- name: Ensure Ghostty config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
    state: directory

- name: Deploy Ghostty config
  template:
    src: config.ghostty.j2
    dest: "{{ ansible_env.HOME }}/.config/ghostty/config"
    backup: true
