- name: Install ghostty
  homebrew:
    name: ghostty
    state: present

- name: Ensure the ghost config directory exsits 
  file:
    path: "{{ ansible_env.HOME }}/.config/ghostty" 
    state: directory

- name: Copy ghostty default config 
  copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/ghostty/config" 
    backup: yes
