- name: Install ghostty
  homebrew_cask:
    name: ghostty
    state: present

- name: Ensure ghostty config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
    state: directory

- name: Copy ghostty config
  template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.config/ghostty/config"
    backup: yes

