- name: Install starship
  homebrew:
    name: starship
    state: present

- name: Copy starship config
  template:
    src: starship.toml.j2
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"

- name: Ensure starship config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/starship"
    state: directory

- name: Copy starship zsh integration
  template:
    src: starship.zsh.j2
    dest: "{{ ansible_env.HOME }}/.config/starship/starship.zsh"

- name: Source starship.zsh from .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "source ~/.config/starship/starship.zsh"
    state: present
