- name: Install neovim
  homebrew:
    name: neovim
    state: present

- name: Ensure nvim config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim" 
    state: directory

- name: Copy the nvim setup default 
  copy:
    src: nvim/ 
    dest: "{{ ansible_env.HOME }}/.config/nvim/" 
    backup: yes
