- name: Install neovim
  homebrew:
    name: neovim
    state: present

- name: Ensure nvim config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim" 
    state: directory

- name: Copy the nvim setup default
  copy:
    src: nvim/
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    backup: yes

- name: Template ui.lua with color variables
  template:
    src: ui.lua.j2
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/plugins/ui.lua"
    backup: yes

- name: Set EDITOR environment variable
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export EDITOR="nvim"'
    state: present
    create: yes
